fixed commerce demo error
simplytestme/website pull request #273
Opened 2023-09-01 08:23 UTC by pkghang

2023-09-01 10:53 UTC, mglaman commented on web/modules/custom/simplytest_tugboat/src/PreviewConfigGenerator.php
> +        'cd stm && composer config allow-plugins true && composer update --no-ansi',
We don't need to do this here, it's a bug due to the legacy Drupal Commerce project template.

2023-09-01 10:54 UTC, mglaman commented on web/modules/custom/simplytest_ocd/tests/src/Unit/CommerceConfigTest.php
> +            'cd stm && composer config allow-plugins true && composer update --no-ansi',
Setting `allow-plugins` shouldn't be needed here

2023-09-01 10:56 UTC, mglaman requested changes
A few requests and test failures

2023-09-01 10:58 UTC, mglaman commented
Build error when manually testing

```
64f1c36e722387719c2cead8# /bin/sh -c cd "${TUGBOAT_ROOT}" && composer create-project drupalcommerce/demo-project stm --no-install --stability dev --no-interaction
Creating a "drupalcommerce/demo-project" project at "./stm"
Info from https://repo.packagist.org: #StandWithUkraine
Installing drupalcommerce/demo-project (dev-master edde71020649ee05caac4b6a08b7f5d0ecc6025f)
- Downloading drupalcommerce/demo-project (dev-master edde710)
- Installing drupalcommerce/demo-project (dev-master edde710): Extracting archive
Created project in /var/lib/tugboat/stm
64f1c36e722387719c2cead8# /bin/sh -c composer config allow-plugins true && composer install
In ConfigCommand.php line 217:
File "./composer.json" cannot be found in the current directory  
                                                                   

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--source] [--] [<setting-key> [<setting-value>...]]
Command Failed (Tugboat Error 1064): Exit code: 1; Command: composer config allow-plugins true && composer install
```

2023-09-01 12:45 UTC, mglaman requested changes
Test failure

```
-            'image' => 'tugboatqa/php:7.3-apache'
+            'image' => 'tugboatqa/php:8.1-apache'
```

1) Drupal\Tests\simplytest_ocd\Unit\UmamiConfigTest::testConfigData

2023-09-01 13:10 UTC, pkghang commented
@mglaman 
- "commerce-kickstart-project" project/plugin will integrate with new feature request ticket.
- PHPUnit test issue fixed
- Also updated the php version for umami test

2023-09-01 13:28 UTC, mglaman requested changes

2023-09-01 13:28 UTC, mglaman commented on web/modules/custom/simplytest_ocd/src/Plugin/OneClickDemo/Commerce.php
> +      'composer config --global allow-plugins true && composer install',
```
64f1e683961ebaf9ec9870c4# /bin/sh -c composer config --global allow-plugins true && composer install
Composer could not find a composer.json file in /var/lib/tugboat
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
```

The previous command uses `'cd "${TUGBOAT_ROOT}" && ` this does as well

2023-09-02 14:12 UTC, mglaman approved these changes
tests need to pass.

2023-09-02 14:12 UTC, mglaman commented on web/modules/custom/simplytest_ocd/tests/src/Unit/CommerceConfigTest.php
> -            'cd stm && composer update --no-ansi',
This is still happening, and should. That's why the test fails. I think.

2023-09-02 14:13 UTC, mglaman requested changes
tests need to be fixed

2023-10-05 13:01 UTC, merged